### ISSUE TITLE
Add ISC Mastodon account to the org's Social accounts

### ISSUE THREAD

**Issue by dellagustin** [InnerSourceCommons/.github#1]
This is part of https://github.com/InnerSourceCommons/InnerSourceMarketing/issues/197.
Please add https://fosstodon.org/@innersource to the org's Social accounts.
With this, the link will show as verified on Mastodon.
Example:
![image](https://user-images.githubusercontent.com/260113/218260189-4a61ea27-1f0a-4c85-9f64-7d4d00d80763.png)

**Comment by dellagustin** [comment]
@claredillon , @spier , @dicortazar , kind of randomly but not so much, picked your names from the org. Could you please take over this one?

**Comment by spier** [comment]
@dellagustin done! See screenshot.

Thanks for handling the mastodon business!

![Screenshot 2023-02-11 at 18 35 18 ](https://user-images.githubusercontent.com/163029/218272652-cacdf872-031a-45ff-81ee-d38072b451f8.png)

**Comment by spier** [comment]
@dellagustin I think you have to remove and add the links on the ISC mastodon account again, in order for mastodon the verification process again.

I will already close this issue here, as from this end it is done.

**Comment by dellagustin** [comment]
> I think you have to remove and add the links on the ISC mastodon account again, in order for mastodon the verification process again.

This comment had a follow up at https://github.com/InnerSourceCommons/InnerSourceMarketing/issues/197#issuecomment-1426880419
